#! /bin/sh
setxkbmap de -option ctrl:nocaps
xbindkeys

bspc config focus_follows_pointer true

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor eDP1 -d 1 2 3 4 5 6 7 8

bspc config border_width         10
bspc config window_gap           10

bspc config active_border_color \#958abe
bspc config normal_border_color \#958abe
bspc config focused_border_color \#958abe

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config top_padding 	30

bspc rule -a KeePassXC state=floating
bspc rule -a Zathura state=tiled
bspc rule -a Emacs state=tiled

# Programs to start
#picom &

# Spotifyd
killall -q spotifyd 
spotifyd 

playerctld daemon &
eww open emibar &

# Multi Monitor
# TODO Can we set up 1-2 mirrored workspaces?
if [[ $(xrandr -q | grep 'HDMI2 connected') ]]; then 
  xrandr --output  eDP1 --primary --auto --rotate normal --output HDMI2 --auto --rotate normal --right-of eDP1 &

  bspc monitor eDP1 -d 1 2 3 4
  bspc monitor HDMI2 -d 5 6 7 8

  eww open emibar_external &
fi

# Wallpaper
feh --bg-scale $HOME/Pictures/Wallpaper/bg1.png

emacsclient -e "(kill-emacs)"
emacs --daemon
