#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8

bspc config border_width         8
bspc config window_gap           8

bspc config active_border_color \#958abe
bspc config normal_border_color \#958abe
bspc config focused_border_color \#958abe

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config top_padding 	30

bspc rule -a KeePassXC state=floating
bspc rule -a Emacs state=tiled

# Programs to start
nextcloud --background &
picom &

# Wallpaper
feh --bg-scale $HOME/Pictures/bg.png

# Spotifyd
killall -q spotifyd 
spotifyd 

playerctld daemon &
eww open emibar &
