#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config top_padding 	30

bspc rule -a KeePassXC state=floating
bspc rule -a Emacs state=tiled

# Programs to start
nextcloud --background &
picom &

# Wallpaper
feh --bg-scale $HOME/Pictures/wedding_carry.png

# Polybar
$HOME/.config/polybar/launch.sh

# Spotifyd
killall -q spotifyd
spotifyd
